# Generated by Django 4.2.5 on 2023-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('fireid', models.CharField(max_length=100)),
                ('balance', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireid', models.CharField(default='', max_length=100)),
                ('todaydate', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=100)),
                ('vehiclename', models.CharField(default='', max_length=100)),
                ('vehiclenum', models.CharField(default='', max_length=100)),
                ('parkingname', models.CharField(default='', max_length=100)),
                ('selecteddate', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('starthour', models.CharField(max_length=100)),
                ('endhour', models.CharField(max_length=100)),
                ('totalcost', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=30)),
                ('valet', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedParkinglot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireid', models.CharField(max_length=100)),
                ('spotname', models.CharField(max_length=100)),
                ('spotaddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=15)),
                ('fireid', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('platenum', models.CharField(max_length=100)),
                ('fireid', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
