# Generated by Django 4.2.5 on 2023-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='floornum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parkingdetails',
            name='spotnum',
            field=models.CharField(default='', max_length=100),
        ),
    ]
