# Generated by Django 4.2.5 on 2023-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_parkingdetails_floornum_parkingdetails_spotnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
