# Generated by Django 4.2.1 on 2023-10-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_parkingdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilephoto',
            field=models.FileField(blank=True, null=True, upload_to='userProfilePhotos/'),
        ),
    ]
