# Generated by Django 4.2.1 on 2023-10-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='displayphoto',
            field=models.FileField(blank=True, null=True, upload_to='displayPhotos/'),
        ),
    ]
