# Generated by Django 4.2.1 on 2023-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_parkingspot_displayphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedparkinglot',
            name='displayphoto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
