# Generated by Django 4.2.1 on 2023-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_savedparkinglot_parkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='displayphoto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
